### ISSUE TITLE
Dynamic event stream for UndoManager

### ISSUE THREAD

**Issue by dlemmermann** [TomasMikula/UndoFX#16]
I was wondering if it is possible to add and remove event streams from the stream that is being used by the UndoManager. In my use case the user is creating a flow diagram and keeps adding nodes to it. Each node has an x and a y property. I want to "monitor" these coordinates via the help of two event streams and I want to add them to the event stream of the undo manager without loosing the current history. How can I do this?

**Comment by TomasMikula** [comment]
Is [`EventStreams.merge`](http://www.reactfx.org/javadoc/2.0-M5/org/reactfx/EventStreams.html#merge-javafx.collections.ObservableSet-) what you are looking for?

**Comment by dlemmermann** [comment]
No because it always returns a new stream. I can not update the stream used
by the undo manager.
Tomas Mikula <notifications@github.com> schrieb am Mo. 24. Apr. 2017 um
20:54:

**Comment by TomasMikula** [comment]
> I can not update the stream used by the undo manager.

You don't need to.

```java
ObservableSet<EventStream<MyChange>> streamSet = FXCollections.observableSet();
EventStream<Change> changes = EventStreams.merge(streamSet);
UndoManager undoManager = UndoManagerFactory.unlimitedHistoryUndoManager(changes, ...);

// later
EventStream<MyChange> newChangeStream = ???;
streamSet.add(newChangeStream);
```

**Comment by dlemmermann** [comment]
Ah perfect. Thank you!
